name: ci

on:
  workflow_dispatch:
    inputs:
      tag:
        description: override release tag
        required: false

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true
permissions:
  contents: write
  id-token: write

jobs:
  test-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9.14.2

      - name: Install dependencies
        run: pnpm install

      - name: Build packages
        run: pnpm build:all

      - name: Create Releases
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Get versions from package.json files
          QUERY_CORE_VERSION=$(jq -r .version packages/query-core/package.json)
          REACT_QUERY_VERSION=$(jq -r .version packages/react-query/package.json)
          
          # Create release for query-core
          gh release create "@ramp/query-core@v${QUERY_CORE_VERSION}" \
            --title "@ramp/query-core@v${QUERY_CORE_VERSION}" \
            --generate-notes \
            packages/query-core/build/*

          # Create release for react-query
          gh release create "@ramp/react-query@v${REACT_QUERY_VERSION}" \
            --title "@ramp/react-query@v${REACT_QUERY_VERSION}" \
            --generate-notes \
            packages/react-query/build/* 